DROP TABLE Producers
DROP TABLE Directors
DROP TABLE Movies
DROP TABLE Play_in
DROP TABLE Plays_in
DROP TABLE Battle_with





CREATE TABLE Heroes
	(HID INT PRIMARY KEY,
	Name VARCHAR(50) UNIQUE,
	Super_power VARCHAR(50),
	Planet VARCHAR(50),
	GAID INT UNIQUE
	)



CREATE TABLE Villans
	(VID INT PRIMARY KEY,
	Name VARCHAR(50) UNIQUE,
	Super_power VARCHAR(50),
	Planet VARCHAR(50),
	BAID INT UNIQUE
	)

CREATE TABLE Battle_with
	(HID INT REFERENCES Heroes(HID),
	VID INT 
	PRIMARY KEY(HID,VID)
	)



CREATE TABLE Battle_with
	(HID INT REFERENCES Heroes(HID),
	VID INT REFERENCES Villans(VID)
	PRIMARY KEY(HID,VID)
	)

	
CREATE TABLE GActors
	(GAID INT PRIMARY KEY,
	FirstName VARCHAR(50) UNIQUE,
	LastName VARCHAR(50) UNIQUE,
	Nationality VARCHAR(50),
	Date_Of_Birth VARCHAR(50),
	HID INT UNIQUE FOREIGN KEY REFERENCES Heroes(HID)
	)

CREATE TABLE BActors
	(BAID INT PRIMARY KEY,
	FirstName VARCHAR(50) UNIQUE,
	LastName VARCHAR(50) UNIQUE,
	Nationality VARCHAR(50),
	Date_Of_Birth VARCHAR(50),
	VID INT UNIQUE FOREIGN KEY REFERENCES Villans(VID)
	)

CREATE TABLE Producers
	(PID INT PRIMARY KEY,
	FirstName VARCHAR(50) UNIQUE,
	LastName VARCHAR(50) UNIQUE,
	Date_Of_Birth DATE,
	)



CREATE TABLE Play_in
	(GAID INT REFERENCES GActors(GAID),
	MID INT REFERENCES Movies(MID)
	PRIMARY KEY(GAID,MID)
	)

CREATE TABLE Plays_in
	(BAID INT REFERENCES BActors(BAID),
	MID INT REFERENCES Movies(MID)
	PRIMARY KEY(BAID,MID)
	)


CREATE TABLE Directors
	(DID INT PRIMARY KEY,
	FirstName VARCHAR(50) UNIQUE,
	LastName VARCHAR(50) UNIQUE,
	Date_Of_Birth DATE,
	)

CREATE TABLE Movies
(MID int primary key,
Release_year VARCHAR(50),
Phase INT,
PID INT UNIQUE FOREIGN KEY REFERENCES Producers(PID),
BID INT UNIQUE FOREIGN KEY REFERENCES Directors(DID),
)


